Fix registrations padding; add registrations header; fix buttons
svthalia/Reaxit pull request #144
Opened 2021-10-19 15:30 UTC by LCKnol

Closes #128 

### Summary

- Adds a "Registrations" header above the registrations in an event.
- Change "No" button to uppercase when cancelling for an event.
- Fix padding to the left and right of registrations to be equal to the rest of the event screen.

2021-11-19 11:09 UTC, DeD1rk commented
So far all of the point in #128 have been dealt with, except:

- [ ] It is not possible to register again for an event that you have cancelled your registration for when the registration deadline has not passed yet (example at the time of writing: Thalympics).


There is also:
> The border of the top information part end in a different spot than the border that split the information and the description.

This is a material design 'middle divider' for medium emphasis grouping in related content, whereas the other one divides the screen in sections (map | info | description | registrations).

2021-11-24 19:20 UTC, TippieCodes requested changes
- Strange opening animation where fade in comes from below on android
- (pubspec.lock) This does not seem to belong in this PR
- (event_screen.dart) Personally I find it better to keep this as the name or maybe prefix it with EVENT:, but leave the name of the event in, this is useful when an event has a longer description or a lot of members and you forgot the name whilst reading the event information.

2021-11-24 19:20 UTC, TippieCodes commented on lib/ui/widgets/menu_drawer.dart
> +                            routerDelegate.push(TypedMaterialPage(
Strange opening animation where fade in comes from below on andriod

2021-11-24 19:20 UTC, TippieCodes commented on pubspec.lock
> -    version: "2.8.2"
This does not seem to belong in this PR

2021-11-24 19:20 UTC, TippieCodes commented on pubspec.lock
> +    version: "0.12.10"
This does not seem to belong in this PR

2021-11-24 19:20 UTC, TippieCodes commented on pubspec.lock
> +    version: "0.4.2"
This does not seem to belong in this PR

2021-11-24 19:20 UTC, TippieCodes commented on lib/ui/screens/event_screen.dart
> -              title: Text(event.title.toUpperCase()),
Personally I find it better to keep this as the name or maybe prefix it with EVENT:, but leave the name of the event in, this is useful when an event has a longer description or a lot of members and you forgot the name whilst reading the event information.

2021-11-24 19:20 UTC, TippieCodes commented on lib/ui/screens/event_screen.dart
> -              title: Text(event.title.toUpperCase()),
This has been decided with available technicie members to revert

2021-11-24 19:33 UTC, TippieCodes commented
Above commit has been discussed and decided by anyone at the technicie meeting

2021-11-24 19:43 UTC, TippieCodes commented on lib/ui/widgets/menu_drawer.dart
> +                            routerDelegate.push(TypedMaterialPage(
Resolving this on this PR, this will be looked at after PR (#157) has been merged

2021-11-24 19:43 UTC, TippieCodes approved these changes

2021-11-24 20:20 UTC, merged