Pay screen
svthalia/Reaxit pull request #363
Opened 2023-03-03 15:57 UTC by JeeVee11

Closes #261.

### Summary
This adds a screen where users can see their outstanding Thalia pay payments.

2023-03-03 16:01 UTC, JAicewizard requested changes

2023-03-03 16:01 UTC, JAicewizard commented on test/mocks.mocks.dart
> +  //     ) as _i5.Stream<_i2.DetailState<_i3.PaymentUser>>);
Are these neccesary? They should either be removed or uncommented

2023-03-03 16:01 UTC, JAicewizard commented on lib/api/concrexit_api_repository.dart
> +        //PaymentType.cardPayment: 'card_payment'
Remove this

2023-03-03 16:03 UTC, JAicewizard commented
Very nice, I will try it out tomorrow.
We will have to figure out what causes the 500 first before merging, but that's for the concrexit team to figure out.

2023-03-03 16:25 UTC, JeeVee11 commented
> Very nice, I will try it out tomorrow. We will have to figure out what causes the 500 first before merging, but that's for the concrexit team to figure out.

So you think it is at the concrexit side? Or is the app making a bad request or something?

2023-03-03 16:28 UTC, DeD1rk commented on test/mocks.mocks.dart
> +  //     );
Probably just need to regenerate generated files

2023-03-03 18:51 UTC, DeD1rk commented
The 500 is indeed a website thing, I'm not exactly sure why it _changed_ but a middleware is failing to set request.member in API requests, and a simple fix is to instead use only request.user. But I would like to know what broke it

2023-03-03 18:51 UTC, DeD1rk commented
I'll probably fix it tomorrow

2023-03-04 10:43 UTC, DeD1rk commented
I've got a fix in https://github.com/svthalia/concrexit/pull/2846

2023-03-04 13:05 UTC, JeeVee11 commented
Nice!

2023-03-04 16:53 UTC, JeeVee11 commented
OK it works now.

2023-03-08 22:18 UTC, JAicewizard commented
Looks good, but tests should be fixed

2023-03-20 19:10 UTC, JAicewizard requested changes
Couple small changes but it looks good. On staging some payments have no data in the extra section, but I'm sure that thats just because they're not present if manually added.

2023-03-20 19:10 UTC, JAicewizard commented on android/app/src/main/kotlin/com/reaxit/MainActivity.kt
> +}
Is this neccesary?

2023-03-20 19:10 UTC, JAicewizard commented on lib/ui/widgets/pay_tile.dart
> +        )),
Add comma in between

2023-03-22 18:25 UTC, JAicewizard approved these changes

2023-03-22 18:25 UTC, merged